package.json, scripts/build/config/linux.json, scripts/build/config/mac.json, scripts/build/config/windows.json, scripts/build/electron-build.js
- Init electron programatic build for integration electron-updater later
=> Add electron programatic build with different platforms configs

src/renderer/components/XCloudPage.vue, src/renderer/logic/FileLogger.js, src/renderer/logic/downloader.js, src/renderer/logic/file.js, src/renderer/logic/uploader.js, src/renderer/logic/utils/notifications.js
=> Dv2 11 event sending UI

package.json, src/renderer/logic/utils/analytics.js, src/sync/filesystems/remote-filesystem.ts, src/sync/sync.ts, src/sync/utils.ts
Fixes and improvements to be made after 1.5.1 release
=> [_]: fix/1.5.1-review

.github/workflows/test.yml
Re-enabled unit test workflow on pull request
=> [_] chore: run unit test on pr

package.json, release/app/package.json
Update package version for the release
=> [WT-147] release: update package json to release

package.json
Run jest unit test silently to improve test result legibility
=> [_] chore: run jest test silently

src/main/analytics/backup-handlers.ts, src/main/analytics/handlers.ts, src/main/analytics/service.ts, src/main/analytics/sync-handlers.ts, src/main/auth/handlers.ts
- Sends only one error with all the info of individual file/folders errors when syncing and backing
- Added `Application Opened` event
=> [WT-196]: Fix/send only one error

src/main/background-processes/backups.ts, src/main/background-processes/sync.ts, src/main/event-bus.ts, src/main/windows/widget.ts, src/test/fixtures/AccessResponse.json, src/test/unauthorized.e2e.ts
- Added test to check unauthorized event is correctly handled 
- Wait for widget to be ready to start background processes so it can listen to unauthorized events
=> [_] fix: unauthorized test

src/main/bug-report/service.ts
Log bug response status in case of not being "OK" to help trace errors
=> [_]: chore/log-bug-report-response-status

src/main/bug-report/BugReportResult.ts, src/main/bug-report/service.ts, src/renderer/pages/ProcessIssues/ReportModal.tsx
When the report limit for the day has reached the message shown was for a generic error.
=> [DT-8] feat: improve error message on reports limit reached

src/main/auth/service.ts, src/main/bug-report/service.ts, src/renderer/pages/Widget/SyncInfo.tsx
Some changes were not correctly merged
=> [_] fix: merge fix

src/workers/sync/Listings/infrastructure/ConfigFileListingStore.ts, src/workers/sync/test/Listings/infrastructure/ConfigFileListingStore.test.ts
Check correctly when the stored listing data does not match the current data required
=> [_] fix: fix old listing validation

src/renderer/pages/Settings/General/SyncRoot.tsx, src/renderer/utils/path.ts, tailwind.config.js
- Now General Settings shows exactly which folder is the main sync folder (It gets truncated if its needed)
=> [DT-54]: Feat/Show exact drive folder path

src/renderer/localize/i18n.service.ts, src/renderer/localize/locales/en.json, src/renderer/localize/locales/fr.json, src/renderer/pages/ProcessIssues/index.tsx, src/renderer/pages/Settings/General/LanguagePicker.tsx
- Added french translation configuration and resources
- Fixed an english translation text
- Fixed bug where LanguagePicker was not showing the button to change Language
=> [PB-71]: Feat/Add FR language

src/renderer/pages/ProcessIssues/List.tsx
- Removed report feedback modal till it gets fixed correctly
=> [PB-84]: Fix/Remove report feedback modal

src/main/database/data-source.ts, src/main/database/entities/DriveFile.ts, src/main/database/entities/DriveFolder.ts, src/main/remote-sync/RemoteSyncManager.test.ts, src/main/remote-sync/helpers.ts, src/workers/filesystems/infrastructure/SyncRemoteFileSystem.ts
Populate listing using the RemoteSyncManager and the local db entities, so we avoid config.json serialization
=> [PB-324]:(feature) Populate listing using local db

src/main/sync-root-folder/handlers.ts
- Folder icon from widget now opens virtual drive root folder
=> [PB-553]: feat/Folder icon now opens virtual drive root folder

src/main/remote-sync/RemoteSyncManager.test.ts
fixes `electron failed to install` on unit test run
=> test: fix electron failed to install

src/renderer/pages/Widget/Header.tsx
- Fixed double folder opened on folder icon clicking (windows)
=> [PB-553]: Fix double folder opened on folder icon clicking

src/main/main.ts, src/main/migration/handlers.ts, src/main/migration/service.ts, src/main/preload.d.ts, src/main/preload.js, src/main/remote-sync/RemoteSyncManager.ts, src/main/windows/migration.ts, src/renderer/localize/locales/en.json, src/renderer/localize/locales/es.json, src/renderer/pages/Migration/index.tsx, src/renderer/pages/Migration/slides/MigrationFailedSlide.tsx, src/renderer/pages/Settings/General/AppInfo.tsx
Start migration flow from the desktop settings with a button
=> [_]:(feature) Allow to start migration from the desktop app settings

src/main/analytics/service.ts, src/main/analytics/user-handlers.ts, src/main/database/data-source.ts, src/main/database/entities/DriveFile.ts, src/main/preload.d.ts, src/main/preload.js, src/main/remote-sync/RemoteSyncManager.ts, src/main/remote-sync/helpers.ts, src/main/windows/feedback.ts, src/main/windows/index.ts, src/renderer/App.tsx, src/renderer/localize/locales/en.json, src/renderer/localize/locales/es.json, src/renderer/pages/Feedback/index.tsx, src/renderer/pages/Widget/Header.tsx, src/shared/HttpClient/HttpClient.ts, tailwind.config.js
Allow users to send feedback via feedback window, can be accesed from widget dropdown menu.
Also HttpClient error interceptor has been modified to throw the received error correctly
=> [PB-506]:(feature) Send feedback window

src/workers/filesystems/domain/ServerFile.ts, src/workers/filesystems/domain/ServerFolder.ts, src/workers/webdav/modules/items/application/RemoteItemsGenerator.ts
Now ServerFile and ServerFolder contains the status
=> [_]:(feature) Add status to ServerFile and ServerFolder

src/main/auth/service.ts, src/main/main.ts, src/main/windows/widget.ts
- Improved sqlite data source re-initialization
- Fixed some auth errors after login out and login in again
=> [PB-631]:(fix) Check for saved configs before accesing properties

src/main/bug-report/handlers.ts, src/main/bug-report/service.ts, src/main/main.ts
- Identify Sentry user
- Enable Sentry only when the app is packaged
=> [_]:(feature) Identify Sentry user on main process

.github/workflows/build-linux.yml, .github/workflows/build-mac-arm.yml
Added missing SENTRY_DSN env to Github Actions workflows files
=> [_]:(fix) Add missing Sentry DSN to Github Actions envs

src/main/background-processes/sync.ts, src/main/preload.d.ts, src/main/preload.js, src/main/remote-sync/RemoteSyncManager.ts, src/main/remote-sync/handlers.ts, src/renderer/hooks/SyncStatus.tsx, src/renderer/localize/locales/en.json, src/renderer/localize/locales/es.json, src/renderer/localize/locales/fr.json, src/renderer/pages/Widget/Header.tsx, src/renderer/pages/Widget/SyncAction.tsx, src/renderer/pages/Widget/SyncFailed.tsx, src/renderer/pages/Widget/index.tsx, tailwind.config.js
- Display remote sync status in the widget
- Display error message if remote sync fails
=> [PB-633]:(feature) Display status of the remote sync, display error if it fails

src/main/analytics/webdav-handlers.ts, src/main/main.ts, src/shared/IPC/events/webdav.ts, src/workers/webdav/index.ts
- Added virtual drive unmount error handler
=> [_]: Added virtual drive unmount error handler

src/main/windows/feedback.ts, src/renderer/components/WindowTopBar.tsx, src/renderer/pages/Feedback/index.tsx
Allow to close feedback window
=> [PB-669]:(fix) Allow to close feedback window

src/main/main.ts, src/main/preload.d.ts, src/main/preload.js, src/main/tray.ts, src/main/windows/auth.ts, src/main/windows/feedback.ts, src/main/windows/index.ts, src/main/windows/migration.ts, src/main/windows/onboarding.ts, src/main/windows/process-issues.ts, src/main/windows/settings.ts, src/main/windows/widget.ts, src/renderer/pages/Login/index.tsx
- Fix widget cleanup logic
- Improve windows cleanup when closed
- Separate widget and login windows
=> [PB-632]:(fix) Separate widget and login windows, improve widget cleanup

src/main/analytics/webdav-handlers.ts, src/main/background-processes/webdav.ts, src/main/platform/handlers.ts, src/main/preload.d.ts, src/main/preload.js, src/renderer/hooks/VirtualDriveStatus.tsx, src/renderer/localize/locales/en.json, src/renderer/localize/locales/es.json, src/renderer/localize/locales/fr.json, src/renderer/pages/Widget/Header.tsx, src/renderer/pages/Widget/VirtualDriveError.tsx, src/renderer/pages/Widget/index.tsx, src/shared/IPC/events/webdav.ts, src/workers/webdav/VirtualDrive.ts, src/workers/webdav/index.ts
- Auto retry virtual drive mounting if it fails
- Display virtual drive not mounted error in the widget
- Disable the open folder button if virtual drive is not mounted
=> [PB-678]:(feature) Auto retry the virtual drive mounting if it fails

src/workers/webdav/VirtualDrive.ts
- Added getCurrentMountedDrives function to reuse already mounted drive
=> [PB-607]: Feat/Reuse already mounted drive

src/main/analytics/webdav-handlers.ts, src/renderer/components/FileWithOperation.tsx, src/renderer/pages/Widget/SyncInfo.tsx, src/shared/IPC/events/webdav.ts, src/workers/types.ts, src/workers/webdav/dependencyInjection/DependencyContainerFactory.ts, src/workers/webdav/modules/files/application/WebdavFileClonner.ts, src/workers/webdav/modules/files/application/WebdavFileCreator.ts, src/workers/webdav/modules/files/application/WebdavFileDeleter.ts, src/workers/webdav/modules/files/application/WebdavFileDownloader.ts, src/workers/webdav/modules/files/application/WebdavFileMover.ts, src/workers/webdav/modules/files/application/WebdavFileRenamer.ts, src/workers/webdav/modules/files/test/application/WebdavFileMover.test.ts, src/workers/webdav/worker/InternxtFileSystem/InternxtFileSystem.ts
- Used webdav events to send changes to sync notifications
- Added renaming logic
- Removed some old sync notification parts
=> [PB-481]: Feat/UI reporting changes

src/main/analytics/webdav-handlers.ts, src/main/background-processes/webdav.ts, src/main/event-bus.ts, src/main/remote-sync/RemoteSyncManager.ts, src/main/remote-sync/handlers.ts, src/shared/IPC/events/webdav.ts, src/workers/webdav/VirtualDrive.ts
Now we can configure if we want the webdav-server to spawn when the user is logged in, or when the initial sync is ready
=> [PB-633]:(feature) Allow to configure webdav-server spawn mode

src/main/analytics/service.ts, src/main/analytics/webdav-handlers.ts, src/shared/IPC/events/webdav.ts, src/shared/types/Stopwatch.ts, src/workers/webdav/modules/files/application/WebdavFileCreator.ts, src/workers/webdav/modules/files/application/WebdavFileDownloader.ts
- Added required metadata for tracking as (file_extension, file_size, etc)
=> [PB-691]: Feat/Add tracking required metadata

src/workers/webdav/modules/files/application/WebdavFileValidator.ts, src/workers/webdav/modules/files/domain/FilePath.ts, src/workers/webdav/worker/InternxtFileSystem/InternxtFileSystem.ts
Exclude files from being created mostly
=> [PB-680](fix): Exlude native OS files

package.json, release/app/package.json, src/main/database/entities/DriveFile.ts, src/workers/webdav/modules/items/application/Traverser.ts
Reset the traverser correctly, this was causing a lot of files and folder to being cached incorrectly
=> [_]: Reset traverser correctly

src/main/background-processes/webdav.ts, src/main/bug-report/service.ts, src/main/main.ts, src/workers/webdav/modules/files/domain/FileStatus.ts
Prevent multiple webdav worker windows that could lead to issues
=> [_]:(fix) Prevent multiple webdav workers

src/workers/filesystems/domain/ServerFolder.ts, src/workers/webdav/modules/folders/infrastructure/HttpWebdavFolderRepository.ts, src/workers/webdav/modules/folders/test/infrastructure/HttpWebdavFolderRepository.test.ts, src/workers/webdav/modules/items/application/RemoteItemsGenerator.ts, src/workers/webdav/modules/items/application/Traverser.ts, src/workers/webdav/modules/items/test/persistance/ServerFolderMother.ts
Changed `updated_at` and `created_at` to `updatedAt` and `createdAt` on server folder. Fixes an error when creating folders
=> [_] fix: change updated and created keys to camel case

package.json, src/workers/webdav/modules/files/application/WebdavFileValidator.ts, src/workers/webdav/worker/InternxtFileSystem/InternxtFileSystem.ts, src/workers/webdav/worker/InternxtFileSystem/Serializer.ts, src/workers/webdav/worker/error-handling.ts, src/workers/webdav/worker/server.ts, yarn.lock
Use @internxt/webdav-server from https://github.com/internxt/webdav-server
=> [_]: Use Internxt webdav-server

src/workers/webdav/VirtualDrive.ts
- Added auto eject MacOS installer disks on VirtualDrive mount
=> [PB-575]: Auto clean MacOS installer disks

package.json, release/app/package.json
=> [_]: Bump version to 2.0.9

src/renderer/pages/Login/service.ts
Send the email in lowercase to avoid an error on the access face of the login
=> [PB-463] fix(login): send email in lower case

src/workers/utils/icon.ts, src/workers/webdav/BindingManager.ts, src/workers/webdav/index.ts
implements https://github.com/internxt/node-win/pull/11
=> [_] feat: set icon path for root folder

src/apps/sync-engine/index.ts, src/apps/utils/icon.ts
Update: add icon path
Why: The drive icon was not being displayed
=> [_]: fix/add drive icon

src/context/virtual-drive/contents/infrastructure/EnvironmentRemoteFileContentsManagersFactory.ts, src/context/virtual-drive/contents/infrastructure/FSLocalFileProvider.ts
Update: modified the wait function to try to load when it is finished being occupied by the windows process
=> [_] fix/wait-busy-files-updated

src/apps/main/config.ts, src/apps/main/virutal-root-folder/service.ts, src/apps/sync-engine/dependency-injection/common/logEnginePath.ts, src/apps/sync-engine/dependency-injection/common/virtualDrive.ts
Update:
- include the log path  of node-win engine.
=> [_]: feat/add-login-path-from-node-win

src/apps/renderer/localize/locales/en.json
- Fixes [PB-1352] 'address' typo
- Fixes [PB-1353] 'Log in' typo
[PB-1352]: https://inxt.atlassian.net/browse/PB-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PB-1353]: https://inxt.atlassian.net/browse/PB-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PB-1352, PB-1323]: Feat/fix typos

package.json, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/context/shared/domain/ServerFile.ts, src/context/virtual-drive/boundaryBridge/application/FileSyncOrchestrator.ts, src/context/virtual-drive/files/application/FileContentsUpdater.ts, src/context/virtual-drive/files/application/FileCreatorFromServerFile.ts, src/context/virtual-drive/files/application/FileSyncronizer.ts, src/context/virtual-drive/files/domain/File.ts, src/context/virtual-drive/files/domain/FileRepository.ts, src/context/virtual-drive/files/domain/events/FileUpdateContentDomainEvent.ts, src/context/virtual-drive/files/domain/file-systems/RemoteFileSystem.ts, src/context/virtual-drive/files/infrastructure/InMemoryFileRepository.ts, src/context/virtual-drive/files/infrastructure/SDKRemoteFileSystem.ts, src/context/virtual-drive/folders/application/Offline/OfflineFolderCreator.ts, src/context/virtual-drive/items/application/RemoteItemsGenerator.ts
Why:
During sync some files change its size
We have to update the content when a file has a different size
What:
Add the update of contents when file size is modified
=> [_]: feat/update-content-sync

src/apps/fuse/FuseApp.ts, src/apps/shared/fs/ensure-folder-exists.ts
https://inxt.atlassian.net/browse/PB-1645
=> [PB-1645] fix: Check if directories (root and temp) exists on start fuseapp

src/apps/sync-engine/dependency-injection/files/FilesContainer.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/context/virtual-drive/files/application/FileIndetityUpdater.ts, src/context/virtual-drive/files/application/FileSyncronizer.ts, src/context/virtual-drive/files/domain/file-systems/LocalFileSystem.ts, src/context/virtual-drive/files/infrastructure/InMemoryFileRepository.ts, src/context/virtual-drive/files/infrastructure/NodeWinLocalFileSystem.ts
- add updateIdentity of nodewin
- add updateIdentity to update content
=> [PB-1925]: Fix/update-fileidentity

src/apps/main/config.ts, src/apps/sync-engine/dependency-injection/files/FilesContainer.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/context/virtual-drive/files/application/FileIndetityUpdater.ts, src/context/virtual-drive/files/application/FileSyncronizer.ts, src/context/virtual-drive/files/domain/file-systems/LocalFileSystem.ts, src/context/virtual-drive/files/infrastructure/InMemoryFileRepository.ts, src/context/virtual-drive/files/infrastructure/NodeWinLocalFileSystem.ts
Update:
- add a flag for the maintenance
Main modification to maintain the integrity of identities:
https://github.com/internxt/node-win/pull/83
=> [PB-2050]: Feat/maintain data integrity

src/apps/main/background-processes/sync-engine.ts, src/apps/main/config.ts, src/apps/main/fordwardToWindows.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/handlers.ts, src/apps/shared/fs/write-readable-to-file.ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks-controllers/controllers/DownloadFileController.ts, src/apps/sync-engine/index.ts, src/apps/utils/runner.ts, src/context/virtual-drive/contents/application/ContentsDownloader.ts
=> [PB-1733]: Feat/part of mix downloading

package.json, release/app/package.json, src/apps/main/auth/handlers.ts, src/apps/main/background-processes/sync-engine.ts, src/apps/main/database/adapters/base.ts, src/apps/main/database/collections/DriveFileCollection.ts, src/apps/main/database/collections/DriveFolderCollection.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/handlers.ts, src/apps/renderer/pages/Widget/index.tsx, src/apps/sync-engine/BindingManager.ts, src/apps/utils/isTemporalFile.ts, src/context/virtual-drive/boundaryBridge/application/FileSyncOrchestrator.ts, src/context/virtual-drive/contents/infrastructure/FSLocalFileProvider.ts, src/context/virtual-drive/files/application/FilesPlaceholderUpdater.ts, src/context/virtual-drive/folders/application/UpdatePlaceholderFolder.ts, src/context/virtual-drive/folders/infrastructure/HttpRemoteFolderSystem.ts
Fixes:
- Resolved the issue with editing Office files (Excel, Word, PowerPoint, etc.) [PB-2709](https://inxt.atlassian.net/browse/PB-2709)
- Fixed the problem where temporary files were being uploaded when editing Office files [PB-2971](https://inxt.atlassian.net/browse/PB-2971)
- Corrected the file restoration process [PB-2903](https://inxt.atlassian.net/browse/PB-2903)
- Fixed the issue where deleted files on the web would sometimes reappear in the app [PB-2963](https://inxt.atlassian.net/browse/PB-2963)
- Resolved the error that prevented deleting and/or moving files [PB-2711](https://inxt.atlassian.net/browse/PB-2711)
- Optimized cloud synchronization [PB-2768](https://inxt.atlassian.net/browse/PB-2768)
[PB-2709]: https://inxt.atlassian.net/browse/PB-2709?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> Bug Resolution

release/app/yarn.lock, src/apps/sync-engine/callbacks/fetchData.service.ts
What:
Delete deprecated function from node-win
=> fix: delete close download mutex function

package.json, release/app/package.json, src/apps/main/preload.d.ts, src/apps/renderer/pages/Onboarding/config.tsx, src/apps/renderer/pages/Settings/Header.tsx, src/apps/renderer/pages/Settings/index.tsx, src/apps/renderer/pages/Widget/Header.tsx
Hide everything related to the Antivirus from the user because it cannot be used until the new plans are released.
=> [_]: feat/hide Antivirus

src/apps/utils/isTemporalFile.ts
Allow non extension files to be updated to the cloud.
=> Allow non extension files

.erb/scripts/convert-hash.py, README.md
These are the new instructions to release the app manually meanwhile we prepare the automation
=> [_]: doc/new release instructions

release/app/yarn.lock, src/context/virtual-drive/contents/application/ContentsUploader.ts, src/context/virtual-drive/contents/application/RetryContentsUploader.ts, src/context/virtual-drive/files/application/FileSyncronizer.ts
What:
this pr allows a message to be displayed on issues related to the storage limit reach, it also prevents retries for this error.
Important considerations: the error is being handled by message and not by status code because the backend cannot guarantee that this code is only associated with storage limit reach errors.
=> fix: show storage limit notification

src/context/virtual-drive/files/application/FileCheckerStatusInRoot.ts, src/context/virtual-drive/files/application/PlaceholderTypes.ts
Fix placeholder types, when importing from node-win in src/context it's throwing an error.
=> Add placeholder types

src/apps/main/background-processes/process-issues.ts
Update asset path retrieval: use process.cwd() instead of __dirname to load assets from the project root.
=> fix: add internxt icon in storage notification

package.json, release/app/package.json, src/apps/renderer/pages/ProcessIssues/index.tsx, src/context/virtual-drive/contents/application/ContentsUploader.ts
- Feature: Added windows toast notifications when the storage limit is reached.
- Bugfix: Separated execution contexts from rename callbacks
=> release: 2.4.3

package.json, src/apps/main/remote-sync/RemoteSyncManager.test.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/files/fetch-files.service.interface.ts, src/apps/main/remote-sync/files/fetch-remote-files.service.ts, src/apps/main/remote-sync/files/fetch-workspace-files.service.ts, src/apps/main/remote-sync/files/sync-remote-files.service.ts, src/apps/main/remote-sync/folders/fetch-folders.service.interface.ts, src/apps/main/remote-sync/folders/fetch-remote-folders.service.ts, src/apps/main/remote-sync/folders/fetch-workspace-folders.service.ts, src/apps/main/remote-sync/folders/sync-remote-folders.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/remote-sync/workspace/fetch-workspaces.service.ts, src/apps/main/remote-sync/workspace/sync-remote-workspace.ts, src/apps/main/virtual-root-folder/service.ts, src/apps/shared/HttpClient/schema.d.ts
- Add remote sync workspace in remote sync Manager
=> Add remote sync workspace

package.json, release/app/package.json, src/apps/main/antivirus/Antivirus.ts, src/apps/main/antivirus/ManualSystemScan.ts, src/apps/main/antivirus/utils/getFilesFromDirectory.ts, src/apps/renderer/hooks/antivirus/useAntivirus.tsx, src/apps/renderer/localize/locales/en.json, src/apps/renderer/localize/locales/es.json, src/apps/renderer/localize/locales/fr.json, src/apps/renderer/pages/Onboarding/config.tsx, src/apps/renderer/pages/Settings/Antivirus/index.tsx, src/apps/renderer/pages/Settings/Antivirus/views/ScanState.tsx, src/apps/renderer/pages/Settings/Header.tsx, src/apps/renderer/pages/Settings/index.tsx
This PR is to show the Antivirus. All users will be able to see this new tool in the settings section within the application.
The users that will be able to use this new tool will be the users that have purchased one of the new plans, as it is a feature that is included in these plans.
=> [_]: feat/enable Antivirus for new plan paid users

package.json, release/app/package.json
What:
Update package.json files to the right app version
=> chore: update package version

package-lock.json, package.json, src/context/local/localFile/infrastructure/EnvironmentLocalFileUploader.ts, src/context/virtual-drive/contents/infrastructure/EnvironmentRemoteFileContentsManagersFactory.ts, yarn.lock
What:
This release pr updates Inxt-js version, and set new multipart threshold to 100MB
=> feat: 2.4.5 release

.github/workflows/pull-request.yml, src/apps/main/virtual-root-folder/service.ts, src/apps/shared/HttpClient/schema.d.ts, src/context/virtual-drive/files/application/FileContentsUpdater.ts
Add github action for prettier.
=> Add prettier pipeline

src/apps/main/preload.js, src/apps/main/windows/ipc/settings-ipc-main.ts
Add path to preload.js so that renderer process can access it.
=> Add path to preload

src/apps/main/bug-report/handlers.ts, src/apps/main/realtime.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/files/sync-remote-files.service.ts, src/apps/main/remote-sync/folders/sync-remote-folders.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/usage/service.ts, src/apps/main/usage/serviceBuilder.ts, src/apps/renderer/components/WindowTopBar.tsx, src/apps/renderer/pages/Widget/Header.tsx, src/apps/shared/IPC/events/account/AccountIpcMain.ts, src/apps/shared/IPC/events/account/AccountIpcRenderer.ts, src/apps/shared/logger/logger.ts, src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/core/env/env.ts, src/types/env.d.ts
1. Delete PHOTOS_URL env variable.
2. Move all logger.info to logger.debug. The point is to start with all in debug and move little by little to info, since those will be stored in S3 and we have to take into account the cost of those logs.
=> Delete PHOTOS_URL env

package.json, src/apps/main/antivirus/ClamAVDaemon.ts, src/apps/main/background-processes/sync-engine.ts, src/apps/main/ipcs/ipcMainAntivirus.ts, src/apps/main/main.ts, src/apps/main/preload.d.ts, src/apps/main/preload.js, src/apps/main/remote-sync/workspace/fetch-workspaces.service.ts, yarn.lock
This Pull Request includes the following updates and improvements:
- Updated the "@internxt/inxt-js" dependency in the package.json file.
- Modified the drive names in the user interface and code.
- Implemented validation logic for the backup functionality.
=> Library Update, Drive Renaming, and Backup Validation

src/apps/main/auth/handlers.ts, src/apps/main/auth/service.ts, src/apps/main/database/data-source.ts, src/apps/main/main.ts, src/apps/main/types.ts, src/apps/renderer/pages/Login/index.tsx
This Pull Request introduces a validation to force users to log out when updating the application. This ensures that users go through the login flow again and retrieve the new keys necessary for the correct functioning of the application.
**Specific Changes:**
- Implementation of validation logic to force logout when updating the application.
**Impact:**
This modification ensures that all users update their keys when updating the application, which improves security and functionality.
=> Implementation of Force Logout for Application Update

nodemon.json, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/files/sync-remote-files.service.test.ts, src/apps/main/remote-sync/files/sync-remote-files.service.ts, src/apps/main/remote-sync/folders/sync-remote-folders.service.test.ts, src/apps/main/remote-sync/folders/sync-remote-folders.service.ts, src/apps/shared/logger/logger.ts, tests/vitest/utils.helper.test.ts
When an error whas thrown when fetching files or folders, it was retyring from offset 0.
=> Fix offset in sync files and folders

src/apps/main/database/collections/DriveFileCollection.ts, src/apps/main/database/collections/DriveFolderCollection.ts
Replace Logger with custom logger
=> Replace Logger with custom logger

src/apps/backups/Backups.ts, src/apps/main/realtime.ts, src/context/virtual-drive/folders/application/FolderCreator.ts, src/context/virtual-drive/folders/application/create/SimpleFolderCreator.ts, src/context/virtual-drive/folders/infrastructure/HttpRemoteFolderSystem.ts
This Pull Request includes two main improvements: the replacement of the Electron logger with a custom logger and the addition of extra parameters when creating offline folders before uploading them to the server.
- Replacement of the Electron logger with the custom logger:
- The default Electron logger has been replaced with a custom logger. This allows greater control over the format and management of logs, facilitating debugging and issue tracking.
- Addition of parameters when creating offline folders:
- The parameters uuid, status, updatedAt and createdAt have been added when creating offline folders before uploading them to the server. This provides more complete and accurate information about offline folders, facilitating their management and synchronization with the server.
=> Logs Refactoring and Offline Folder Creation Improvement

src/apps/main/background-processes/sync-engine/services/get-workspaces.test.ts, src/apps/main/background-processes/sync-engine/services/get-workspaces.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.test.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.ts, src/apps/main/virtual-root-folder/service.ts, src/core/electron/paths.ts
Remove brackets from workspace root path, since watcher (chokidar) was not working.
=> Remove brackets from workspace path

.erb/configs/webpack.config.main.prod.ts, README.md, package.json
This Pull Request includes two main changes: updating the package version and modifying the webpack in the main file to add node-loader.
- Package version update:
- The package version has been updated to the latest available version. This ensures that the latest features and bug fixes are used.
- Webpack modification in main:
- The webpack in the main file has been modified to add node-loader. This allows for the correct loading of Node.js modules in the main application context.
=> Package Version Update and Webpack Modification in Main

package.json, pnpm-lock.yaml, src/apps/main/remote-sync/handlers.ts
Specific Changes:
- Updated the Node.js version for the Windows build.
- Refactored and improved the reset logic of the Remote Sync Manager.
=> Update Node Win Version and Improve Remote Sync Manager Reset Logic

package.json, pnpm-lock.yaml, src/apps/main/background-processes/spawn-all-sync-engine-workers.test.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.test.ts, src/apps/main/logger.ts, src/core/electron/paths.ts
Revert logs so they are split into main.log and renderer.log.
=> Revert logs

package.json, pnpm-lock.yaml, src/apps/main/device/service.ts, src/apps/main/fordwardToWindows.ts, src/apps/main/logger.ts, src/apps/main/main.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/shared/logger/custom-inspect.ts, src/apps/sync-engine/index.ts, src/context/virtual-drive/contents/infrastructure/download/EnvironmentContentFileDownloader.ts, src/core/electron/paths.ts
Try again using logger.initialize but now setting the paths manually to internxt-drive/drive-desktop.ans. It's working for me, we can test during these days and revert again if not working in a stable way.
=> Improve logger

package.json, pnpm-lock.yaml, src/apps/main/auth/handlers.ts, src/apps/main/auth/service.ts, src/apps/main/background-processes/sync-engine.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.test.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.ts, src/apps/main/preload.d.ts, src/apps/main/preload.js, src/apps/main/remote-sync/handlers.ts, src/apps/shared/logger/logger.ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks/handleAdd.service.ts, src/apps/sync-engine/callbacks/handleDehydrate.service.ts, src/apps/sync-engine/callbacks/handleHydrate.service.ts, src/apps/sync-engine/dependency-injection/common/virtualDrive.ts, src/context/virtual-drive/files/infrastructure/NodeWinLocalFileSystem.ts, src/context/virtual-drive/folders/infrastructure/NodeWinLocalFolderSystem.ts, src/core/electron/paths.ts
This Pull Request introduces improvements to Windows compatibility, method structure, and internal path management.
- Update node-win version
- Modification of Parameters in node win Methods
- Resolution of Issue in Obtaining PersistQueue Path:
- A minor error affecting how the persistQueue path was obtained has been resolved. This fix ensures that the application accesses the correct location of the persistence queue, which is crucial for task management and data persistence.
=> Update node-win version, Refactor nde-win Method Parameters, and Fix PersistQueue Path Issue

src/apps/backups/Backups.ts, src/apps/backups/dependency-injection/virtual-drive/registerRemoteTreeServices.ts, src/apps/backups/fetch-items/fetch-files-by-folder.test.ts, src/apps/backups/fetch-items/fetch-files-by-folder.ts, src/apps/backups/fetch-items/fetch-folders-by-folder.test.ts, src/apps/backups/fetch-items/fetch-folders-by-folder.ts, src/apps/backups/fetch-items/fetch-items-by-folder.test.ts, src/apps/backups/fetch-items/fetch-items-by-folder.ts, src/apps/backups/fetch-items/fetch-items.ts, src/apps/main/background-processes/sync-engine/services/get-workspaces.test.ts, src/apps/main/background-processes/sync-engine/services/spawn-sync-engine-worker.test.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.test.ts, src/apps/main/device/service.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/files/fetch-remote-files.service.ts, src/apps/main/remote-sync/handlers.ts, src/apps/renderer/hooks/backups/useBackups.tsx, src/apps/shared/IPC/events/sync-engine.ts, src/context/shared/infrastructure/crypt.test.ts, src/context/virtual-drive/items/application/RemoteItemsGenerator.ts, src/context/virtual-drive/remoteTree/application/RemoteTreeBuilder.ts, src/context/virtual-drive/remoteTree/application/Traverser.ts, src/infra/drive-server-wip/out/retry-wrapper.ts, src/infra/drive-server-wip/services/folders.service.ts, tests/vitest/mocks.helper.test.ts, tests/vitest/setup.helper.test.ts
Extract fetch items of backups from outside sync engine. Now, they are two different functions. Also, now fetching the backups data doesn't add it to the database. However, the files and folders are going to still be added to the sqlite since when we do the remote sync we also fetch files and folders from drive and backups.
=> Improve fetch backup items

src/apps/backups/dangled-files/DangledFilesService.test.ts, src/apps/main/thumbnails/infrastructure/EnvironmentAndStorageThumbnailUploader.ts, src/apps/renderer/pages/Widget/Item.tsx, src/context/virtual-drive/contents/application/ContentsDownloader.ts
This Pull Request introduces changes to the texts displayed to the user during the file download process.
- Change in progress texts:
- The texts indicating the download progress have been modified. The goal of this change is to make the information clearer, more accurate, and more intuitive for the user, better reflecting the stages of the download process.
=> Changed Texts to Display Download Progress

README.md, package.json, src/apps/backups/utils/relative.ts, src/apps/main/background-processes/issues.ts, src/apps/main/ipcs/ipcMainSyncEngine.ts, src/apps/shared/issues/VirtualDriveIssue.ts, src/apps/sync-engine/BindingManager.ts, src/context/virtual-drive/folders/infrastructure/dtos/client.dto.ts
1. Fix ts-prune so it shows an error when there is dead code.
2. Add deepwiki so we have auto documentation.
=> Fix ts-prune

package.json, src/apps/sync-engine/dependency-injection/files/builder.ts, src/apps/sync-engine/dependency-injection/folders/builder.ts, src/context/virtual-drive/files/application/FIlePlaceholderConverter.ts, src/context/virtual-drive/files/application/FileCheckerStatusInRoot.ts, src/context/virtual-drive/files/application/FilesPlaceholderDeleter.test.ts, src/context/virtual-drive/files/application/FilesPlaceholderDeleter.ts, src/context/virtual-drive/files/infrastructure/NodeWinLocalFileSystem.ts, src/context/virtual-drive/folders/application/FolderPlaceholderConverter.ts, src/context/virtual-drive/folders/application/FolderPlaceholderDeleter.ts, src/context/virtual-drive/folders/infrastructure/NodeWinLocalFolderSystem.ts
Add FilePlaceholderDeleter tests.
=> Add file placeholder deleter tests

package.json, pnpm-lock.yaml, src/apps/main/remote-sync/handlers.ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/dependency-injection/folders/builder.ts, src/context/virtual-drive/files/application/update/FilesPlaceholderUpdater.ts, src/context/virtual-drive/folders/application/update/UpdatePlaceholderFolder.test.ts, src/context/virtual-drive/folders/application/update/UpdatePlaceholderFolder.ts, src/context/virtual-drive/items/application/RemoteItemsGenerator.ts
1. Update node-win version 1.0.12.
2. Create folder placeholders only when they are not synced.
=> Create folder placeholders if not synced

.erb/scripts/electron-launcher.js, package.json, pnpm-lock.yaml, sonar-project.properties
Upgrade to node 20 and electron 29
=> Upgrade to node 20 and electron 29

src/apps/shared/IPC/events/sync-engine.ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/in/get-placeholders-with-pending-state.ts, src/node-win/addon-wrapper.ts, src/node-win/virtual-drive.ts
Migrate getPlaceholdersWithPendingState from C++ to javascript.
=> Move get pending placeholders to js

examples/handlers/handle-add.ts, examples/handlers/handle-change-size.ts, examples/handlers/handle-dehydrate.ts, examples/register.ts, src/apps/main/background-processes/sync-engine/services/schedule-sync.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/remote-sync/helpers.ts, src/apps/sync-engine/BindingManager.ts, src/context/virtual-drive/folders/application/FolderPlaceholderDeleter.ts, src/node-win/addon-wrapper.ts, src/node-win/addon.ts, src/node-win/queue/queueManager.ts, src/node-win/virtual-drive.ts, src/node-win/virtual-drive.unit.test.ts
This Pull Request implements two key changes to improve data synchronization speed and reliability.
- Reduced Sync Rewind:
- The sync "rewind" period has been reduced from 30 to 2 minutes. This change allows the application to process recent changes more quickly, resulting in faster synchronization and less delay in update propagation.
- Changed Sync Cron Frequency:
- The sync cron job execution time has been modified to run every 10 minutes. This adjustment aims to reduce the sole dependency on the socket for updates, providing a robust, periodic synchronization mechanism that ensures data stays up-to-date even if the socket connection experiences interruptions.
=> This Pull Request implements two key changes to improve data synchronization speed and reliability.

package.json, pnpm-lock.yaml, src/apps/main/auth/handlers.ts, src/apps/main/background-processes/backups/launchBackupProcesses.ts, src/apps/renderer/pages/Settings/Backups/Selector/BackupItem.tsx
1. Fix bug that was showing "Find folder" in backups when you were selecting another device. This button should only be visible when you are on your device.
2. Fix bug that if you click fast in "Stop backup" maybe the abort controller wasn't listening yet.
=> Allow stop backups since the beginning

src/apps/main/realtime.ts, src/apps/main/usage/handlers.ts, src/apps/main/usage/service.test.ts, src/apps/main/usage/service.ts, src/infra/drive-server-wip/services/user.service.ts, src/node-win/addon-wrapper.ts, src/node-win/addon.ts, src/node-win/addon/addon-zod.ts
1. Simplify get usage and limit using retryWrapper.
2. Add addon zod to check that response from C++ has the right format.
=> Retry usage and limit and addon zod

package.json, sonar-project.properties, src/apps/main/antivirus/scan-file.ts, src/apps/main/antivirus/scanCronJob.ts, src/apps/main/antivirus/utils/dbConections.ts, src/apps/main/antivirus/utils/initializeAntivirus.ts, src/apps/main/antivirus/utils/transformItem.ts
Extract scanFile function in antivirus and improve logs.
=> Extract scan file in antivirus

.eslintrc.js, package.json, src/infra/drive-server-wip/drive-server-wip.module.test.ts, src/infra/drive-server-wip/in/client-wrapper.service.ts, src/infra/drive-server-wip/in/client-wrapper.test.ts, src/infra/drive-server-wip/in/get-in-flight-request.test.ts, src/infra/drive-server-wip/in/get-in-flight-request.ts, src/infra/drive-server-wip/services/auth.service.ts, src/infra/drive-server-wip/services/backup.service.ts, src/infra/drive-server-wip/services/backup/create-device.ts, src/infra/drive-server-wip/services/backup/get-device.ts, src/infra/drive-server-wip/services/files.service.ts, src/infra/drive-server-wip/services/folders.service.ts, src/infra/drive-server-wip/services/folders/create-folder.ts, src/infra/drive-server-wip/services/storage.service.ts, src/infra/drive-server-wip/services/user.service.ts, src/infra/drive-server-wip/services/workspaces.service.ts, tsconfig.json
Remove duplicated requests by using a Map.
=> Get in flight request

src/apps/backups/fetch-items/fetch-files-by-folder.ts, src/apps/backups/fetch-items/fetch-folders-by-folder.ts, src/infra/drive-server-wip/in/client-wrapper.service.ts, src/infra/drive-server-wip/in/client-wrapper.test.ts, src/infra/drive-server-wip/in/exception-wrapper.ts, src/infra/drive-server-wip/in/helpers/error-helpers.ts, src/infra/drive-server-wip/out/error.types.ts, src/infra/drive-server-wip/services/folders.service.ts
Now we are handling the abort error in fetch requests. Also, backups now abort all remotes fetch in case the user aborts the backup.
=> Add abort requests

src/apps/backups/folders/create-folders.test.ts, src/apps/backups/folders/create-folders.ts, src/apps/sync-engine/callbacks-controllers/controllers/AddController.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/context/local/localFile/application/upload/FileBatchUploader.ts, src/context/virtual-drive/boundaryBridge/application/FileCreationOrchestrator.ts, src/context/virtual-drive/files/application/FileCreator.ts, src/context/virtual-drive/files/application/FileOverwriteContent.ts, src/context/virtual-drive/files/domain/OfflineFile.ts, src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/context/virtual-drive/folders/application/FolderFinder.ts, src/context/virtual-drive/folders/infrastructure/HttpRemoteFolderSystem.ts, src/infra/drive-server-wip/services/files.service.ts, src/infra/drive-server-wip/services/folders/create-folder.test.ts, src/infra/drive-server-wip/services/folders/create-folder.ts, src/infra/drive-server-wip/services/workspaces.service.ts, src/node-win/addon-wrapper.ts, src/node-win/watcher/detect-context-menu-action.service.ts, src/node-win/watcher/events/on-raw.service.ts, tests/context/virtual-drive/files/application/FileCreator.test.ts
Remove FolderFinder in create-file, now it looks for the folder uuid in the file explorer instead of the in memory.
=> Create file remove folder finder

src/context/virtual-drive/contents/application/RetryContentsUploader.ts, src/context/virtual-drive/contents/application/contents-downloader.test.ts, src/context/virtual-drive/contents/infrastructure/download/EnvironmentContentFileDownloader.ts, src/context/virtual-drive/contents/infrastructure/download/environment-content-file-downloader.test.ts, src/context/virtual-drive/contents/infrastructure/upload/environment-content-file-uploader.test.ts, src/context/virtual-drive/files/application/file-creator.test.ts, src/context/virtual-drive/files/application/file-deleter.test.ts, src/context/virtual-drive/files/application/file-path-updater.test.ts, src/context/virtual-drive/files/domain/File.ts, src/context/virtual-drive/files/domain/file-path.test.ts, src/context/virtual-drive/files/domain/file-size.test.ts, src/context/virtual-drive/folders/application/folder-deleter.test.ts, src/context/virtual-drive/folders/application/folder-mover.test.ts, src/context/virtual-drive/shared/application/PlatformPathConverter.test.ts, src/context/virtual-drive/shared/application/absolute-path-to-relative-converter.test.ts, src/context/virtual-drive/shared/domain/path.test.ts, tests/context/__mocks__/contents-size-mother.helper.test.ts, tests/context/__mocks__/download-strategy-function-mock.helper.test.ts, tests/context/__mocks__/file-contents-mother.helper.test.ts, tests/context/__mocks__/upload-strategy-function-mock.helper.test.ts, tests/context/virtual-drive/files/domain/FileMother.ts
Revert tests that were deleted.
=> Revert tests

src/apps/sync-engine/BindingManager.ts, src/context/virtual-drive/files/application/update/FilesPlaceholderUpdater.test.ts, src/context/virtual-drive/files/application/update/FilesPlaceholderUpdater.ts
Simplify files placeholder updater since remote can only be EXISTS.
=> Simplify files placeholder updater

src/apps/main/antivirus/antivirus-manager/select-antivirus-engine.ts, src/apps/main/antivirus/windows-defender/antivirus-windows-defender.test.ts, src/apps/main/antivirus/windows-defender/antivirus-windows-defender.ts, src/apps/main/antivirus/windows-defender/find-mcp-command.test.ts, src/apps/main/antivirus/windows-defender/find-mcp-command.ts, src/apps/main/antivirus/windows-defender/is-windows-defender-available.ts
Improved error handling when MpCmdRun.exe is missing, fallback to alternate antivirus
=> Refactor antivirus engine selection and error handling for MpCmdRun

package-lock.json, package.json, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/refresh-item-placeholders.ts, src/backend/features/remote-sync/file-explorer/delete-item-placeholders.test.ts, src/backend/features/remote-sync/file-explorer/delete-item-placeholders.ts, src/backend/features/remote-sync/sync-items-by-checkpoint/load-in-memory-paths.test.ts, src/backend/features/remote-sync/sync-items-by-checkpoint/load-in-memory-paths.ts, src/context/virtual-drive/files/application/FileCreator.ts
This PR is just to facilitate the next one. Basically here we extract the process of building the tree and updating and deleting all placeholders into a separate function.
=> Extract refresh item placeholders

package.json, src/apps/main/database/entities/DriveFile.ts, src/apps/main/database/entities/DriveFolder.ts, src/apps/main/remote-sync/handlers.ts, src/apps/shared/IPC/events/sync-engine.ts, src/apps/sync-engine/dependency-injection/DependencyContainerFactory.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/apps/sync-engine/dependency-injection/folders/builder.ts, src/apps/sync-engine/dependency-injection/items/builder.ts, src/backend/features/remote-sync/file-explorer/delete-item-placeholders.test.ts, src/backend/features/remote-sync/file-explorer/delete-item-placeholders.ts, src/backend/features/remote-sync/file-explorer/update-file-placeholder.test.ts, src/backend/features/remote-sync/file-explorer/update-file-placeholder.ts, src/backend/features/remote-sync/file-explorer/update-folder-placeholder.test.ts, src/backend/features/remote-sync/file-explorer/update-folder-placeholder.ts, src/context/virtual-drive/files/application/FileOverwriteContent.ts, src/context/virtual-drive/files/infrastructure/InMemoryFileRepository.ts, src/context/virtual-drive/items/application/Traverser.test.ts, src/context/virtual-drive/items/application/Traverser.ts, src/node-win/virtual-drive.ts, src/node-win/virtual-drive.unit.test.ts
Start using the `ExtendedDriveFile` type instead of the `File` class in the traverser.
=> Simplify traverser
