internxt/drive-desktop

.electron-vue/dev-runner.js, .eslintrc.js, resources/osx/notarize.js, src/libs/autolauncher.js, src/main/index.js, src/renderer/components/ConfigPage.vue, src/renderer/components/LandingPage.vue, src/renderer/components/LoginPage.vue, src/renderer/logic/crypt.js, src/renderer/logic/downloader.js, src/renderer/logic/inxtdeps.js, src/renderer/logic/monitor.js, src/renderer/logic/sync.js, src/renderer/logic/tree.js, src/renderer/logic/watcher.js
This is just mainly a visual cleanup and will probably require to make a similar PR based on the `new-drive-desktop` branch though since many of the files have been removed there.
Changes:
- Added an eslint rule to prefer `const` instead of `let` whenever a variable is not reassigned and updated all existing cases that matched that rule.
-  Fixed a few typos throughout the code
- Removed all instances of `var` from the code and changed them for `const`/`let`.
=> Prefer const and fix some typos

src/index.ejs
`electron-vue` has this open issue: https://github.com/SimulatedGREG/electron-vue/issues/871
Trying to build the app in a node version higher than 10.21.0 will result in the following error:
```
Html Webpack Plugin:
ReferenceError: process is not defined
- index.ejs:11 eval
[.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
- index.ejs:16 module.exports
[.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
- index.js:284 
[drive-desktop]/[html-webpack-plugin]/index.js:284:18
- task_queues.js:97 processTicksAndRejections
internal/process/task_queues.js:97:5
```
This PR changes the way the process variable is accessed, allowing the app to build correctly on the old and new node versions.
=> Fix access to process

src/renderer/logic/uploader.js
While troubleshooting a failed upload I couldn't help but notice the string interpolation was wrong for these errors.
=> Fix filesize errors

src/renderer/logic/utils/analytics.js
Adds anonymousId to forgot password track.
Tested on dev environment and on a build version.
Solves: exception risen by Segment analytics-node library when a userId not present.
=> Fix forgot password track

src/workers/backups/backups.ts, src/workers/backups/test/backups.test.ts, src/workers/filesystems/local-filesystem.ts, src/workers/filesystems/remote-filesystem.ts, src/workers/process.ts, src/workers/sync/listing-store.ts, src/workers/sync/sync.ts, src/workers/sync/test/sync.test.ts, src/workers/types.ts
- Start including size alongside modtime in process listings 
- Use that size to filter small files and parallelise its upload with parameters SMALL_FILE_THRESHOLD and PARALLEL_QUEUES
=> [DD-94]: feature/faster-backups-with-small-files

src/main/realtime.ts
Ignore events on the root sync folder. Additionally if the root sync folder is deleted add a warn on the app logs
=> [WT-45] fix: ignore root folder events

src/renderer/pages/Widget/Header.tsx
Maintain the order on menu items as it was before (on v1.5.0)
=> [WT-147] fix: menu order and onboaring text

src/workers/filesystems/remote-filesystem.ts
- Enables to send plain_name with files data (folders plain_name is managed in drive-server)
=> [WT-145]  feature/Added plain_name to uploaded/renamed files

src/main/auth/service.ts, src/main/usage/service.ts, src/renderer/hooks/Usage.tsx
Due we were not storing the `new token` the user will need to log out and log in again in order to be able to get the total usage of his account.
Also, since the check for if the user is logged in is asynchronous it was leading to checking the account usage at startup when was not logged in
=> [_] fix: photos usage

src/workers/utils/name-verification.ts, src/workers/utils/test/name-verification.test.ts
Nested folders are not correctly validated on windows due to the validation method was not prepared to handle OS specific paths.
Solved by sanitizing/converting the path to a UNIX like path before sanitazing
=> [WT-246] fix: sanitize paths before validating them

src/main/background-processes/lock-erros.ts, src/main/background-processes/locks-service.ts, src/main/background-processes/sync.ts, src/renderer/pages/Widget/SyncErrorBanner.tsx
Added descriptive messages when the folder lock requests fail:
The messages are:
| Cause | Response Status | Message Displayed |
--------|----------|----------
| The service failed to lock the folder | 503 | We cannot perform the action at the moment, please try again later |
| The folder is already locked | 409 | Looks like other of your devices are already syncing, we'll try again later
| User is unauthorized | 401 | Your session has expired, if the app does not log out shortly please log out manually*
| An unknown error has occurred | any of the above nor 200 | An unknown error has occurred
(*) The user should be automatically prompted with the login page but since it's done via an event it is possible that it takes a little bit
=> [_]: fix/add-descriptive-lock-error-messages

ignored-files.json
Added 2 ignore patterns:
* "\*.photoslibrary/\*": Files like Phots Library.photolibray (provably present on most macOS users Pictures folder) is, in reality, a [package](https://en.wikipedia.org/wiki/Package_(macOS)). In short, we treat it like a folder. But since is filled with program files it most probably has lots of empty files.
* "\*.localized": 
> .localized files is a localization file used by some macOS system directories. It contains no data. The presence of an empty LOCALIZED file allows macOS to show a system directory's name in a user's preferred language. Do not delete LOCALIZED files stored in macOS system directories.
[source](https://fileinfo.com/extension/localized)
If any user tries to sync or backup a macOS system directory as could be Pictures or Documents will run …
=> [_]: feat/ignore-macos-packages

src/main/auth/refresh-token.ts, src/main/auth/service.ts, src/main/config.ts, src/main/realtime.ts, src/main/usage/service.ts
Don't encrypt tokens when safe storage is not available. Added the key `newTokenEncrypted` to the app config to know if the new Token was encrypted or not
=> [DT-26] fix: dont encrypt tokens when safe storage is not available

src/main/background-processes/backups.ts, src/renderer/actions/backsups-error-actions.ts, src/renderer/actions/shared-actions.ts, src/renderer/actions/sync-error-actions.ts, src/renderer/actions/types.ts, src/renderer/hooks/FatalErrorActions.ts, src/renderer/pages/ProcessIssues/List.tsx, src/shared/types/Process.ts
When a backup folder was renamed the folder id was sent as the error name making the UI not work.
I also refactored the issues actions to be able to show different actions depending on the process, and show an action to change the backup folder path instead of the sync root one
=> [DT-34] Fix: blank issues page when renaming backed folder

.github/workflows/test.yml, src/shared/HttpClient/http-client.test.ts
Since to run the unit test we don't need the native dependencies we can (for now) not try to build them
=> [_ ] fix: run unit test

src/renderer/pages/Onboarding/index.tsx, src/test/onboarding.e2e.ts
When the register flow was changed, the user name is no longer asked on the registration process and defaults to "My".
This will cause the onboarding to show the message `Welcome to Internxt, My!` on the onboarding if the user does not change his name before opening the app.
So it's changed to simply `Welcome to Internxt!`
=> [_] fix: remove the user name from the onboarding

src/workers/filesystems/domain/FileSystem.ts, src/workers/filesystems/infrastructure/SyncRemoteFileSystem.ts
The changes made to know the file id to be able to create thumbnails had to be applied to `SyncRemoteFileSystem`
=> chore: return the file id from pull file

src/main/auto-launch/linux-desktop-entry.ts, src/main/auto-launch/service.ts, src/renderer/pages/Settings/General/StartAutomatically.tsx
To enable the application auto start on Linux a file is needed to be created on `.config/autostart`.
Adds and removes the .desktop file and checks if it is present to determine if auto-start is enabled.
This solution has the downside that we cannot clean this configuration when the app is uninstalled, so a further installation would maintain the configuration of the previous installation
=> [_] feat: reenable auto start on linux

src/workers/filesystems/infrastructure/SyncLocalFileSystem.ts, src/workers/sync/index.ts, src/workers/sync/sync.ts
Filter folders out when doing a resync and use previous file systems.
When both file systems are empty the listing is not created, to create the listing a resync is needed to pull the first files. Once those files are on both file systems normal synchronizations will be executed
=> [_] fix: resync

src/main/device/service.ts
`ParsedPath` name is `The file name without extension (if any) such as 'index'`, that creates an issue when a selected folder has a dot on it (ex: `folder . with a dot`) where it treats the second part from the dot as an extension and it gets deleted from the name, the base property contains the extension part, but the selected items are constrained to folders
=> [_] fix: use base instead of name property from the selected folder

src/workers/filesystems/application/PullFolderQueueConsumer.ts, src/workers/filesystems/domain/FileSystem.ts, src/workers/filesystems/infrastructure/SyncLocalFileSystem.ts, src/workers/filesystems/infrastructure/SyncRemoteFileSystem.ts, src/workers/sync/index.ts, src/workers/sync/sync.ts
Introduced a method to get folder information from the FS in order to get the modification time when pulling a folder.
Added the modification of the folders on the local FS after the creation of them
Fixed error when trying to pull a folder that already exists. This was the case when a local folder had a modification time older than the remote one
=> [PB-69] fix: update folder modtime on local

src/workers/filesystems/application/PullFolderQueueConsumer.ts, src/workers/filesystems/test/__mocks__/FileSystemMock.ts, src/workers/filesystems/test/application/PullFolderQueueConsumer.test.ts, src/workers/sync/Actions/application/ActionBuilders/KeepMostRecentActionBuilder.ts, src/workers/sync/test/Actions/application/GenerateHierarchyActions.test.ts, src/workers/sync/test/sync.test.ts
Modified KeepMostRecent to avoid pulling folders with different modtime as the remote file system can update it. And updated test to match new beheviour
=> fix: avoid pulling folders with different modtime

src/workers/sync/Listings/application/ListingsAreInSync.ts
Folders were not saved in listings due in the remote listings appeared as size 0 and remote modtime cannot be modified via the API
=> [_] fix: listing in sync check

src/workers/sync/sync.ts
Sometimes, even if a file was successfully uploaded does not appear in the current remote listing, generating a wrong diff for the listings to save
=> [PB-69] added timer to try to fix desync from listings local and remote

src/workers/filesystems/infrastructure/SyncRemoteFileSystem.ts
Destroy the stream received on the source so the temporal file created is deleted when the is an error on the remote FS `pullFile`
=> [PB-62] fix: delete tmp files when remote fs pull file fails

src/main/windows/widget.ts
The login popup window stays open on the desktop after losing focus
=> [PB-577] fix: don't hide the login window when it loses focus

src/main/auth/service.ts, src/renderer/App.tsx
Check for user existence before trying to get the keys length, some errors were thrown when user is null and we try to do `Object.keys(user)`
=> [PB-583]:(fix) Check for user correctly from config.json

src/workers/webdav/index.ts
- Fixed Windows empty drive by removing StorageManager (which seem to have incompatibilities on Windows)
=> [PB-589]: Fix/Windows empty drive

src/main/analytics/service.ts, src/main/analytics/webdav-handlers.ts
There was a missing export, and missing arguments in the `trackWebdavError` function
=> [PB-584]:(fix) Fix webdav error handling

src/main/background-processes/webdav.ts, src/workers/webdav/index.ts
Send event to webdav worker using webContents API instead of ipcWebdav
=> [PB-634](fix): Use webContents API to send events to the webdav worker

src/main/platform/handlers.ts
Added a workaround on Linux to open an external URL in the browser due to this [issue](https://github.com/electron/electron/issues/28436). But this can produce some unexpected behavior as depending the way the browser are installed xdg-open may fail to open the default one.
More info on the [Jira task](https://inxt.atlassian.net/browse/PB-556)
=> [PB-556] fix: workaround open external url in linux

src/main/background-processes/webdav.ts, src/workers/webdav/VirtualDrive.ts
- Moved the ejection of the MacOS installer disks to the 'APP_IS_READY' event
=> [PB-717]: Eject installer disks on app start

src/main/realtime.ts
- Connect to notifications server with newToken (drive-server is now fixed)
=> [PB-705]: Refresh folder after notification event

src/workers/webdav/VirtualDrive.ts, src/workers/webdav/worker/server.ts
- Server is now created with the hostname 'Virtual.Drive.Internxt.com' which points to localhost ip. It's a temporary solution to the Finder name problem while we find another better solution
=> [PB-604]: Feat/Show "Virtual Drive" instead of localhost

src/main/main.ts
Fix from the 2.0.0-a03 version where after logging out and back in the app crashed. The problem seems to be that after logging out when the user logs back in 2 widgets were created
=> [_] fix: login broke the app

src/main/background-processes/sync-engine.ts, src/workers/webdav/index.ts
***Context*** 
When we exit the app we need to stop the sync engine from watching the folder and we need to unregister the sync provider. Both of those tasks are done in the sync engine background process so we need to await a message from that process to know that it has been done. 
***Problem***
When the setup of the syn engine fails we cannot add the handler to stop the engine so when the main process tries to close it, it awaits a promise that will never be fulfilled.
***Proposed solution***
Communicate to the main process whether the setup of the sync engine has been successful or not to await the stop message when it has been successful.
Also changed the import of virtual drive dependency to a `require` so it can be part of the setup function since the build of node-win can be …
=> [_] fix: do not block exit if not runing

.github/workflows/test.yml, package.json
Updates the test ci to run on Windows and changes the build to only build the main and renderer processes since node-win is installed from local machines
=> [🧪] run test on ci

src/main/app-info/service.ts
https://github.com/electron/electron/pull/37821 solves the problem with the `getPreferredSystemLanguages` method signature. We no longer need to override it
=> [_] chore: undo app type overwrite

src/main/background-processes/sync-engine.ts, src/main/main.ts, src/workers/webdav/BindingManager.ts, src/workers/webdav/index.ts
ℹ️  This PR needs the changes on https://github.com/internxt/node-win/pull/14
***Problem***
After logging out and logging back in or starting the app without being logged and login in crashes the app.
***Why***
Found out that when we close all windows the local server that serves the UI closes and then when we create another window it cannot load the page making the app crash
***Solution***
On the `USER_LOGGED_IN` event I changed the order of the creation of the widget window and the deletion of the auth window.
***Side effects***
As of now, we can log out and back in without the app crashing during the testing found out that we were not closing the background process correctly. Also solved in this pr
=> [_] fix: app crashes loading the localhost

src/workers/sync-engine/dependency-injection/DependencyContainerFactory.ts, src/workers/sync-engine/dependency-injection/boundaryBridge/build.ts, src/workers/sync-engine/dependency-injection/common/eventHistory.ts, src/workers/sync-engine/dependency-injection/files/FilesContainer.ts, src/workers/sync-engine/dependency-injection/files/builder.ts, src/workers/sync-engine/dependency-injection/shared/SharedContainer.ts, src/workers/sync-engine/dependency-injection/shared/builder.ts, src/workers/sync-engine/modules/boundaryBridge/application/FileCreationOrchestrator.ts, src/workers/sync-engine/modules/files/application/FilePathUpdater.ts, src/workers/sync-engine/modules/files/application/SameFileWasMoved.ts, src/workers/sync-engine/modules/files/domain/File.ts, src/workers/sync-engine/modules/files/domain/FilePath.ts, src/workers/sync-engine/modules/files/domain/events/FileMovedDomainEvent.ts, src/workers/sync-engine/modules/files/infrastructure/HttpFileRepository.ts, src/workers/sync-engine/modules/files/test/application/FilePathUpdater.test.ts, src/workers/sync-engine/modules/shared/application/LocalFileIdProvider.ts, src/workers/sync-engine/modules/shared/domain/EventRepository.ts, src/workers/sync-engine/modules/shared/infrastructure/InMemoryEventHistory.ts
**Why:**
When a file has been moved, after the move is done we get a file creation callback.
**How:**
Added a rename file domain event that stores a combination of the local file data, the `dev`, and `ino` values.
When a file is going to be created it searches if there is a file on the destination. If it exists search for a _move_ event and compares the `dev` and `ino`. If they are the same the file that is going to be created is ignored and the id of that file is returned
=> [] fix: ignore file creation after move

src/workers/sync-engine/modules/items/application/AllStatusesTraverser.ts, src/workers/sync-engine/modules/placeholders/infrastructure/VirtualDrivePlaceholderCreator.ts
**Issue:** 
When performing a synchronization from the remote items (after a notification arrived) deleted folders and files were shown on the file explorer.
**Why:**
On the traverse of all items regardless of the status folders and files that were in a deleted or trashed folder were included. Once in the synchronization, a placeholder for those folders and files was created as they had the status `EXISTS`.
When a placeholder for a folder or a file is created and the folders containing them do not exist Windows creates it as well.
For example, if I create a placeholder for a file with the path `\my_folder\my_file.txt` and the folder my_folder does not exist it will be created (without an ID controlled by us).
**Proposed solution:**
When traversing all the remote items if a folder does not …
=> [PB-1077] Fix: dont create placeholders from deleted items

src/context/virtual-drive/folders/application/FolderCreator.ts, src/context/virtual-drive/folders/domain/FolderPath.ts, src/context/virtual-drive/folders/domain/OfflineFolder.ts, src/context/virtual-drive/folders/infrastructure/HttpRemoteFileSystem.ts, src/context/virtual-drive/shared/domain/Path.ts
Context:
In the creation of folders, we have been using the name provided by` path.posix.parse(folderPath`). However, for folders, it seems better to use basename since it provides the base name of the folders. Only use name in the case of files, as we want it without an extension
=> [_]: fix/use basename insted of name to create folders

src/apps/main/background-processes/process-issues.ts, src/apps/main/fordwardToWindows.ts, src/apps/renderer/localize/locales/en.json, src/apps/renderer/localize/locales/es.json, src/apps/renderer/localize/locales/fr.json, src/apps/renderer/messages/process-error.ts, src/apps/renderer/pages/ProcessIssues/List.tsx, src/apps/renderer/pages/Widget/Item.tsx, src/apps/shared/IPC/events/sync-engine.ts, src/apps/shared/types.ts, src/apps/sync-engine/dependency-injection/common/traverser.ts, src/apps/sync-engine/dependency-injection/items/builder.ts, src/context/virtual-drive/items/application/Traverser.ts, src/context/virtual-drive/items/domain/FolderNode.ts, tests/context/virtual-drive/items/application/Traverser.test.ts
**Why**
On web, we can create files and folders with the same name but on desktop, we cannot due how the OS File System does not allow it.
**Proposed solution**
Ignore one of the "duplicated" elements and notify the user that we cannot sync both of them.
=> [PB-1489] Fix: ignore nodes with same name

src/apps/sync-engine/callbacks-controllers/buildControllers.ts, src/apps/sync-engine/callbacks-controllers/controllers/DeleteController.ts, src/apps/sync-engine/dependency-injection/files/FilesContainer.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/apps/sync-engine/dependency-injection/folders/FoldersContainer.ts, src/apps/sync-engine/dependency-injection/folders/builder.ts, src/apps/sync-engine/index.ts, src/context/virtual-drive/files/application/FileDeleter.ts, src/context/virtual-drive/files/application/FileFolderContainerDetector.ts, src/context/virtual-drive/folders/application/FolderContainerDetector.ts, src/context/virtual-drive/folders/application/FolderFinder.ts, src/context/virtual-drive/folders/application/Offline/OfflineFolderCreator.ts, src/context/virtual-drive/folders/application/RetryFolderDeleter.ts, src/context/virtual-drive/folders/domain/errors/MaxRetriesDeletingFolderError.ts, src/context/virtual-drive/shared/domain/DelayQueue.ts
Context:
- Emited events from node-win to delete files, It is verified that there are no folders pending deletion in the queue so a loop was triggered.
Update:
- Retry mechanism to avoid error on deleting folders
- Remove folders from queue when a folder father is received
- Remove always files from queue if its folder was added in folder queue
- Always remove folder from  queue when is executed to delete from remote
- We should create the tree of folder with error during deleting.
=> [PB-1513]: Fix/loop-when-delete-files

src/apps/main/main.ts
Since Windows and Linux don't have the same version on production the app will try to get the latest yml for its platform on the latest version available in GitHub. If the latest version is not the one for that platform it will not be found and an error will thrown. That error was not being handled
=> [PB-1671] fix: catch errors from auto update

package.json, release/app/package.json, release/app/yarn.lock, src/apps/main/fordwardToWindows.ts, src/apps/main/tray/handlers.ts, src/apps/renderer/localize/locales/en.json, src/apps/renderer/localize/locales/es.json, src/apps/renderer/localize/locales/fr.json, src/apps/renderer/pages/Widget/Item.tsx, src/apps/shared/IPC/events/drive.ts, src/apps/shared/IPC/events/sync-engine.ts, src/apps/shared/fs/write-readable-to-file.ts, src/apps/shared/types.ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks-controllers/controllers/DownloadFileController.ts, src/context/virtual-drive/contents/application/ContentsDownloader.ts, src/context/virtual-drive/contents/domain/contentHandlers/ContentFileDownloader.ts, src/context/virtual-drive/contents/infrastructure/FSLocalFileWriter.ts, src/context/virtual-drive/contents/infrastructure/download/EnvironmentContentFileDownloader.ts, tests/context/virtual-drive/contents/__mocks__/ContentFileDownloaderMock.ts, tests/context/virtual-drive/contents/application/ContentsDownloader._test.ts, yarn.lock
- Removed the force download as @cg27shokworks mentioned it was not being used to simplify the callback
- Moved the tracker record for download after the await of the await of the write, just to simplify too
- Added a check when the writer ends writing the stream, so if the downloaded file does not have the expected size it fails. After that I could not get any errors in the download (I don't think the change made it work but could not test it).
=> patch: this awaits for files to download ?

src/apps/main/preload.d.ts, src/apps/main/preload.js, src/apps/main/remote-sync/helpers.ts, src/apps/renderer/pages/Widget/Header.tsx, src/context/virtual-drive/shared/application/PollingMonitorStart.ts
Why: 
The Sync manula should work only if a process already passed by a time and not during a syncing process
Updates:
- add contiion to not permit when recently was syncing
- add syncing recently by three minutes
=> [_]: manual-sync-permission-delay

src/apps/main/preload.d.ts, src/apps/main/preload.js, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/remote-sync/helpers.ts, src/apps/renderer/pages/Widget/Header.tsx, src/apps/sync-engine/BindingManager.ts, src/context/virtual-drive/files/application/FileCheckerStatusInRoot.ts, src/context/virtual-drive/shared/application/PollingMonitorStart.ts, src/context/virtual-drive/shared/domain/PollingMonitor.ts
Issue:
- fallback was running when items were syncing 
update:
- add permission to avoid running the fallback when something in syncing
=> [_]: Feat/fallback permission

src/apps/main/auth/handlers.ts, src/apps/main/auth/service.ts, src/apps/shared/Delay.ts, yarn.lock
Adds 1-second delay as suggested by a comment for a workaround  on https://github.com/electron/electron/issues/32206
=> [PB-1977] fix: SIGTRAP when calling safe storage methods

src/apps/main/auth/handlers.ts, src/apps/main/auth/service.ts, src/apps/main/preload.js
In addition to the user data being in the config.json also checks if all the tokens are present on the file to set the user as logged
=> [PB-1980] Bugfix: onboaring screen render loggin

src/apps/main/remote-sync/handlers.ts
Instead of delaying the synchronization after the first notification, it's delayed if more notifications arrive in a given threshold
=> [_] feat/debounce remote manager sync

src/apps/main/analytics/user-handlers.ts, src/apps/main/database/adapters/base.ts, src/apps/main/database/collections/DriveFileCollection.ts, src/apps/main/database/collections/DriveFolderCollection.ts, src/apps/main/remote-sync/RemoteSyncManager.test.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/remote-sync/helpers.ts
To avoid prs that depend on other prs. This one removes the StorageApp for the `RemoteSyncManager` and changes the checkpoint of files and folders to be 6 hours before the last updated item.
The StorageApp has been deleted and instead of managing the `lastFilesSyncAt` and `lastFoldersSyncAt`, we take advantage of the local database to query those values. This avoids showing the onboarding window on every login, the reset of the selected language, and the creation of new devices after logging out and back in.
When fetching the items we check for items 6 hours previous to the latest one saved to avoid missing some items when the backend does not return them on the synchronization.
=> [_] fix: ensure newer files are included

package.json, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks/fetchData.service.test.ts, src/apps/sync-engine/callbacks/fetchData.service.ts, tsconfig.json, vitest.config.mts, yarn.lock
1. Add vitest, create vitest.config.mts and add vitest globals in tsconfig.
2. Add vitest-mock-extended.
3. Extract fetch data into it's own service.
1. As talked with @sg-gs, we are able to reduce the time of testing from around 30s to around 3s (this has already been tried and it's happening).
2. Most of the testing done in drive-desktop creates files inside folders called __mocks__ that basically mock the classes so later then can be used for testing. However, this classes need to be mantained, and usually have type errors, since the mock it's not the real class. vitest-mock-extended allow us to create mocks on fly that match the type. This will allow us to write faster tests since we won't need to rely on creating manually all these mocks.
3. Code should be testeable. This is based on …
=> Implement fetch data test and solve a path bug

src/apps/renderer/hooks/antivirus/useAntivirus.tsx
This PR implements a loading state while checking if the user van use the antivirus and initializing the clam av daemon.
=> [_]; fix/loading state while initializing antivirus

src/apps/main/background-processes/sync-engine.ts, src/apps/main/database/collections/DriveFileCollection.ts, src/apps/main/database/collections/DriveFolderCollection.ts, src/apps/main/database/entities/DriveWorkspace.ts, src/apps/main/fordwardToWindows.ts, src/apps/main/realtime.ts, src/apps/main/remote-sync/handlers.ts, src/apps/main/remote-sync/workspace/sync-remote-workspace.ts, src/apps/main/virtual-root-folder/service.ts, src/apps/renderer/pages/Widget/Header.tsx, src/apps/shared/HttpClient/HttpClient.ts, src/apps/shared/IPC/events/drive.ts, src/apps/shared/IPC/events/sync-engine.ts, src/apps/shared/fs/PathTypeChecker .ts, src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks/fetchData.service.ts, src/apps/sync-engine/callbacks/handleAdd.service.ts, src/apps/sync-engine/index.ts, src/context/virtual-drive/files/application/FilePathUpdater.ts, src/context/virtual-drive/files/domain/File.ts, src/context/virtual-drive/folders/application/FolderContainerDetector.ts, src/context/virtual-drive/folders/application/FolderFinder.ts, src/context/virtual-drive/folders/application/FolderPathUpdater.ts, tests/context/virtual-drive/files/application/FilePathUpdater.test.ts
**This Pull Request addresses several issues and improvements in folder and file management:**
- Fix Duplicate Folder Creation:
The error causing duplicate creation of the "New Folder" folder when creating a new folder has been fixed. Now, the handlerAdd returns an error, skipping the queue task and preventing duplication.
- Add WorkspaceID in SYNCED and SYNCING Events:
The WorkspaceID has been added to the synced and syncing events to provide information about the sync status of each individual drive.
- Fix File Rename:
The issue preventing correct file renaming after renaming the parent folder has been fixed.
- Fix Folder Delete in Workspaces:
The issue preventing correct folder deletion within workspaces has been fixed.
- Fix Workspace Entry/Exit Inconsistency:
The inconsistency …
=> Fix Duplicate Folder Creation, WorkspaceID in Events, and File Rename

.gitignore, src/apps/main/auth/handlers.ts, src/apps/main/config.ts, src/apps/main/database/data-source.ts, src/apps/main/virtual-root-folder/service.ts, src/apps/main/virtual-root-folder/services.test.ts, tests/vitest/setup.helper.test.ts
**This Pull Request focuses on fixing an issue that caused the loss of unsynchronized files on login, and on improving sync folder management for existing and new users.**
- Removal of sync root folder deletion on login:
- The logic that deleted the user's sync root folder during login has been removed. This prevents the loss of files that have not yet been synchronized with the cloud.
- Implementation of unique user folders:
- To prevent file mixing between multiple accounts, each user now has a unique sync folder named "InternxtDrive - {userEmail}".
- Folder renaming for legacy users:
- Logic has been implemented to rename existing sync folders of legacy users to the new format.
- Addition of tests:
- Unit tests have been added to ensure the correct functioning of the changes.
- Removal …
=>  Removal of Sync Root Folder Deletion on Login and Renaming for Legacy Users

src/apps/main/main.ts, src/apps/main/virtual-root-folder/service.ts, src/apps/main/virtual-root-folder/services.test.ts
- Initialization of global configuration in main:
The global configuration has been initialized in the main file to ensure that all global values, including the mnemonic and other relevant values, are accessible by default.
- Root folder renaming:
At Luis's request, the key for root folders has been changed from "internxtDrive - user.email" to "InternxtDrive - user.uuid". This improves consistency and uniqueness of folder names.
- Test updates:
The corresponding unit and integration tests have been updated to reflect the changes made.
1. Initialization of global configuration in the main file.
2. Modification of the root folder key to "InternxtDrive - user.uuid".
3. Updating of unit and integration tests.
=> Global Configuration Refactoring and Root Folder Renaming

src/apps/main/fordwardToWindows.ts, src/apps/main/tray/handlers.ts, src/apps/shared/IPC/events/drive.ts, src/apps/shared/IPC/events/sync-engine.ts, src/apps/sync-engine/callbacks/fetchData.service.ts, src/context/virtual-drive/contents/application/ContentsDownloader.ts, src/context/virtual-drive/contents/application/ContentsUploader.ts, src/context/virtual-drive/contents/domain/ContentsManagersFactory.ts, src/context/virtual-drive/contents/infrastructure/EnvironmentRemoteFileContentsManagersFactory.ts, tests/context/virtual-drive/contents/application/ContentsDownloader.test.ts
This Pull Request focuses on simplifying the handling of file download-related events.
- Removal of the FILE_PREPARING event:
- The FILE_PREPARING event has been removed. Now, all download operations exclusively use the FILE_DOWNLOADING event. This simplifies the logic and reduces complexity in handling download events.
=> Removal of FILE_PREPARING Event and Exclusive Use of FILE_DOWNLOADING

.eslintrc.js, src/apps/backups/Backups.ts, src/apps/main/background-processes/backups/launchBackupProcesses.ts, src/apps/main/device/service.ts, src/apps/main/network/NetworkFacade.ts, src/apps/main/network/download.ts, src/apps/main/network/download.types.ts, src/apps/main/network/downloadv2.ts, src/apps/main/remote-sync/files/sync-remote-files.service.ts, src/apps/main/remote-sync/folders/sync-remote-folders.service.ts, src/apps/sync-engine/callbacks/fetchData.service.ts, src/context/local/localFile/application/update/FileBatchUpdater.ts, src/context/local/localFile/application/upload/FileBatchUploader.ts, src/context/local/localTree/application/LocalTreeBuilder.ts, src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/migrations/migrate.ts
1. Simplify download methods and types.
2. Also remove the download for shares since we don't have that feature implemented yet and probably we will need to do some refactoring before applying it.
3. Remove `no-await-in-loop` in eslint.
=> Simplify download and fix types

CONTRIBUTING, src/apps/backups/Backups.ts, src/apps/main/background-processes/sync-engine.ts, src/apps/main/remote-sync/files/sync-remote-file.ts, src/apps/main/remote-sync/folders/folder-store.test.ts, src/apps/main/remote-sync/folders/folder-store.ts, src/apps/main/remote-sync/folders/sync-remote-folder.ts, src/apps/main/remote-sync/handlers.ts, src/apps/shared/logger/logger.ts, src/apps/sync-engine/index.ts, src/context/virtual-drive/files/domain/File.ts, src/infra/drive-server-wip/services/folders.service.ts
1. Improve logger so it only prints workspaceId or tag if they are defined (we now exclude empty workspaceId, so that the default drive doesn't include workspaceId: '' always).
2. Create placeholders as we fetch. We have created an in memory store, that saves all folders so we can retrieve the path recursively. Also, as we fetch we send an IPC signal to the worker to create the placeholder.
3. Add to the CONTRIBUTING file how we are going to make comments.
=> Create placeholders as we fetch

src/apps/main/remote-sync/files/fetch-files.service.interface.ts, src/apps/main/remote-sync/files/fetch-remote-files.service.ts, src/apps/main/remote-sync/files/fetch-workspace-files.service.ts, src/apps/main/remote-sync/files/sync-remote-file.ts, src/apps/main/remote-sync/files/sync-remote-files.service.test.ts, src/apps/main/remote-sync/files/sync-remote-files.service.ts, src/apps/main/remote-sync/folders/fetch-folders.service.interface.ts, src/apps/main/remote-sync/folders/sync-remote-folder.ts, src/apps/main/remote-sync/folders/sync-remote-folders.service.test.ts, src/apps/main/remote-sync/folders/sync-remote-folders.service.ts, src/apps/main/remote-sync/helpers.ts, src/apps/shared/HttpClient/schema.d.ts, src/apps/shared/types/Primitives.ts, src/context/shared/domain/AggregateRoot.ts, src/context/shared/domain/ValueObject.ts, src/context/shared/domain/value-objects/ValueObject.ts, src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/context/virtual-drive/items/application/Traverser.test.ts, src/context/virtual-drive/items/application/Traverser.ts, src/infra/drive-server-wip/drive-server-wip.module.ts, src/infra/drive-server-wip/out/dto.ts, src/infra/drive-server-wip/services/workspaces.service.ts
1. Override schema.d.ts so file.size is marked as string. Then, wherever we need to use this size, convert it to Number(x).
2. Add root folder to traverser.
=> Fix size bigint and root folder in traverser

src/context/virtual-drive/contents/infrastructure/EnvironmentRemoteFileContentsManagersFactory.ts, src/context/virtual-drive/contents/infrastructure/FSLocalFileProvider.ts, src/context/virtual-drive/contents/infrastructure/upload/EnvironmentContentFileUploader.ts, tests/context/virtual-drive/contents/infrastructure/upload/EnvironmentContentFileUploader.test.ts
This Pull Request introduces an improvement to the logic that determines if a file has been modified before attempting to upload it, with the primary goal of preventing upload blocks caused by false positives.
- Change in modification detection logic to avoid false positives:
- The logic used to verify if a file has been changed before initiating the upload has been refactored. The main objective of this modification is to prevent files that have not actually been modified from being incorrectly flagged as such, which could previously block the upload process. The new logic aims for more accurate detection to ensure that only genuine modifications trigger an upload.
=> Refactored Logic for Detecting File Modification During Upload to Prevent False Positives

src/context/virtual-drive/files/application/FilesPlaceholderDeleter.ts
Fix bug in which we were not deleting local placeholders because we were comparing against contentsId instead of uuid.
=> Fix delete local placeholders

src/apps/main/database/entities/DriveFile.ts, src/apps/main/database/entities/DriveFolder.ts
Revert changes about workspaceId being only empty string and disallowing null in the database. We will handle this in the future.
=> Set workspace id as nullable

src/apps/main/notification-schema.ts, src/apps/main/realtime.ts
Currently, we were having a problem because, for example, folders created in backups were dispatching the notification of FOLDER_CREATED and executing the debounceSynchronization when it was not necessary. This was also happening with items created in windows.
Now, we are using the clientId property of the notification. If the value is `drive-desktop` it means we performed the action so it's not necessary to do the synchronization. This is also the beginning of start parsing the notifications and being able to perform the event action in realtime, without having to wait for the full synchronization.
=> Ignore notifications made by drive-desktop

package.json, src/apps/backups/fetch-items/fetch-files-by-folder.test.ts, src/apps/backups/fetch-items/fetch-files-by-folder.ts, src/apps/backups/fetch-items/fetch-folders-by-folder.test.ts, src/apps/backups/fetch-items/fetch-folders-by-folder.ts, src/apps/backups/fetch-items/fetch-items-by-folder.test.ts, src/apps/backups/fetch-items/fetch-items-by-folder.ts, src/apps/backups/fetch-items/fetch-items.ts, src/apps/backups/remote-tree/traverser.ts, src/apps/main/background-processes/backups/BackupsProcessStatus/BackupsStatus.ts, src/apps/main/background-processes/backups/launchBackupProcesses.ts, src/apps/main/remote-sync/handlers.ts, src/apps/renderer/components/Backups/DetailedDevicePill.tsx, src/apps/renderer/pages/Settings/Backups/SelectedFoldersSection.tsx, src/apps/renderer/pages/Settings/Backups/StartBackup.tsx
1. Add abort signal when fetching backup files and folders so it stops when stopping backups.
2. Add STOPPING backup status.
3. Set the backup status as STOPPING immediately when aborting backups.
=> Add abort signal to fetch backup items

src/apps/main/logger.ts, src/core/utils/convertUTCDateToGMT2.test.ts, src/core/utils/convertUTCDateToGMT2.ts, src/core/utils/logFormatter.test.ts, src/core/utils/logFormatter.ts
Added gmt+2 to the logs in order to have the same timezone as the servers.
----
```bash
[2025-06-12T10:44:28.362Z] { level: 'debug', process: 'main', tag: 'BACKUPS', msg: 'Setting up backups' }
[2025-06-12T10:44:28.376Z] [BACKUPS] Start service
[2025-06-12T10:44:28.381Z] [BACKUPS] Backups ready
[2025-06-12T10:44:28.406Z] { level: 'debug', process: 'main', msg: 'User identified for error reporting' }
[2025-06-12T10:44:28.593Z] { level: 'debug', process: 'main', msg: 'Current root virtual drive', current: 'C:\\Users\\inxt\\InternxtDrive - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\\' }
[2025-06-12T10:44:28.596Z] { level: 'debug', process: 'main', msg: 'Add workspace to the folder store', rootId: xxx, rootUuid: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' }
[2025-06-12T10:44:28.599Z] { level: 'debug', …
```
=> [PB-4515] feat: add gmt+2 to logs

package.json, src/apps/main/background-processes/spawn-default-sync-engine-worker.test.ts, src/apps/main/background-processes/sync-engine.ts, src/apps/main/background-processes/sync-engine/services/spawn-sync-engine-worker.ts, src/apps/main/background-processes/sync-engine/services/spawn-workspace.ts, src/apps/main/database/entities/DriveFile.ts, src/apps/main/remote-sync/RemoteSyncManager.ts, src/apps/main/remote-sync/files/sync-remote-file.ts, src/apps/main/remote-sync/files/sync-remote-files.test.ts, src/apps/main/remote-sync/files/sync-remote-files.ts, src/apps/main/remote-sync/folders/sync-remote-folder.ts, src/apps/main/remote-sync/folders/sync-remote-folders.test.ts, src/apps/main/remote-sync/folders/sync-remote-folders.ts, src/apps/main/remote-sync/handlers.ts, src/apps/sync-engine/config.ts, src/backend/features/remote-sync/sync-items-by-folder/update-file-statuses.test.ts, src/backend/features/remote-sync/sync-items-by-folder/update-file-statuses.ts, src/backend/features/remote-sync/sync-items-by-folder/update-folder-statuses.test.ts, src/backend/features/remote-sync/sync-items-by-folder/update-folder-statuses.ts, src/backend/features/remote-sync/update-in-sqlite/create-or-update-file.ts, src/backend/features/remote-sync/update-in-sqlite/create-or-update-folder.ts
Now, since we have move the checkpoint outside the sqlite database we can create files and folders in the background sync.
=> Create file or folder in background sync

CONTRIBUTING, src/apps/backups/Backups.ts, src/apps/main/antivirus/antivirus-manager/get-active-antivirus-engine.test.ts, src/apps/main/antivirus/antivirus-manager/get-active-antivirus-engine.ts, src/apps/main/antivirus/antivirus-manager/select-antivirus-engine.test.ts, src/apps/main/antivirus/antivirus-manager/select-antivirus-engine.ts, src/apps/main/device/service.ts, src/apps/main/logger.ts, src/apps/main/main.ts, src/apps/main/network/get-file-info.ts, src/apps/renderer/hooks/backups/useBackups.tsx, src/apps/shared/logger/logger.ts, src/apps/sync-engine/dependency-injection/common/virtualDrive.ts, src/backend/features/auth/services/logout.service.test.ts, src/backend/features/auth/services/logout.service.ts, src/backend/features/remote-notifications/in/process-web-socket-event.test.ts, src/backend/features/remote-notifications/in/process-web-socket-event.ts, src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/core/electron/paths.ts, src/node-win/logger.ts
Basically we are going to remove `ans` because when the size of the file is big it takes too much time to load colors. Also, using the extension .log already uses colors in vscode.
=> Move from ans to log in logger

src/apps/sync-engine/BindingManager.ts, src/apps/sync-engine/callbacks-controllers/controllers/add-controller.ts, src/apps/sync-engine/config.ts, src/apps/sync-engine/dependency-injection/files/builder.ts, src/apps/sync-engine/dependency-injection/folders/builder.ts, src/apps/sync-engine/in/add-pending-files.ts, src/apps/sync-engine/in/add-pending-folders.ts, src/apps/sync-engine/in/add-pending-items.ts, src/apps/sync-engine/index.ts, src/apps/sync-engine/tests/create-placeholder.infra.test.ts, src/context/virtual-drive/boundaryBridge/application/FileCreationOrchestrator.ts, src/context/virtual-drive/files/application/FileCreator.ts, src/context/virtual-drive/files/application/file-creator.test.ts, src/context/virtual-drive/folders/application/FolderCreator.test.ts, src/context/virtual-drive/folders/application/FolderCreator.ts, src/features/sync/add-item/create-file.ts, src/features/sync/add-item/create-folder.ts, src/node-win/watcher/events/on-add-dir.service.test.ts, src/node-win/watcher/events/on-add-dir.service.ts, src/node-win/watcher/events/on-add.service.ts, src/node-win/watcher/watcher.helper.test.ts, src/node-win/watcher/watcher.ts
Start sending `ctx` using prop drilling to we can stop using getConfig and migrate the sync engine process to main.
=> Migrate to context

src/context/virtual-drive/files/infrastructure/HttpRemoteFileSystem.ts, src/context/virtual-drive/files/infrastructure/restore-parent-folder.ts, src/infra/drive-server-wip/in/client-wrapper.service.ts, src/infra/drive-server-wip/services/files/create-file.test.ts, src/infra/drive-server-wip/services/files/create-file.ts, src/infra/drive-server-wip/services/files/rename-folder.ts, src/infra/drive-server-wip/services/folders.service.ts, src/infra/drive-server-wip/services/workspaces.service.ts, src/infra/drive-server-wip/services/workspaces/create-file.ts
Fix two issues when restoring parent folder:
1. If we have moved the folder and is has been marked as TRASHED for some reason. When we move back and rename it maybe the name was already right and it throws an error. This has happen to me when doing a test for the release.
2. When an error because of the rename, move or whatever, it enters in the catch and tries to do the getFileByPath which also fails because the problem was the folder or other thing. Now we just execute the getFileByPath if the create-file endpoint gives a 409 (conflict, file already exists).
=> Fix restore parent folder

package-lock.json, package.json, src/apps/main/auth/handlers.ts, src/apps/main/auth/headers.ts, src/apps/main/auth/refresh-token.ts, src/apps/main/auth/service.ts, src/apps/main/payments/get-available-products.ts, src/apps/main/realtime.ts, src/apps/main/token-scheduler/TokenScheduler.ts, src/apps/main/token-scheduler/token-scheduler.test.ts
Since now we have removed `bearerToken` we can just use the default token `newToken` instead of working with an array of tokens.
=> Use only new token

src/apps/sync-engine/file-explorer-state/file-explorer-state.types.ts, src/apps/sync-engine/file-explorer-state/get-file-explorer-state.ts, src/apps/sync-engine/file-explorer-state/is-hydration-pending.test.ts, src/apps/sync-engine/file-explorer-state/is-hydration-pending.ts, src/apps/sync-engine/file-explorer-state/is-modified.test.ts, src/apps/sync-engine/file-explorer-state/is-modified.ts, src/apps/sync-engine/file-explorer-state/process-item.test.ts, src/apps/sync-engine/file-explorer-state/process-item.ts, src/infra/file-system/services/sync-walk.test.ts, src/infra/file-system/services/sync-walk.ts
This is the first of 3 PRs that are going to simplify the way we read the current file explorer state and perform actions based on that on the sync process start. Currently we were checking if a file or folder did not have a placeholder and in that case we were creating them. We were also checking if the size of the remote file was different from the local one and update contents id in that case. And finally we were using a queue mananger to keep track of files that were pending for hydration so we can hydrate them when the app starts again.
Now, we are going to join all 4 into the same function so we just iterate the sync folder just one time. Also, we are going to stop using the queue manager since we are going to check the PinState of a file in the explorer and the number of blocks it …
=> Get file explorer state

package.json, src/apps/main/windows/broadcast-to-windows.d.ts, src/apps/renderer/localize/locales/en.json, src/apps/renderer/localize/locales/es.json, src/apps/renderer/localize/locales/fr.json, src/apps/renderer/pages/Widget/Item.tsx, src/apps/shared/HttpClient/schema.ts, src/backend/features/local-sync/watcher/events/rename-or-move/get-parent-uuid.test.ts, src/backend/features/local-sync/watcher/events/rename-or-move/get-parent-uuid.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-file.test.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-file.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-folder.test.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-folder.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-item.test.ts, src/backend/features/local-sync/watcher/events/rename-or-move/move-item.ts, src/context/virtual-drive/files/infrastructure/restore-parent-folder.test.ts, src/context/virtual-drive/files/infrastructure/restore-parent-folder.ts, src/infra/drive-server-wip/out/ipc-main.ts, src/infra/drive-server-wip/out/ipc.ts, src/infra/drive-server-wip/services/files.service.ts, src/infra/drive-server-wip/services/files/move.ts, src/infra/drive-server-wip/services/folders.service.ts, src/infra/drive-server-wip/services/folders/move.ts
Now the move endpoint also accepts the name and extension for files and the name for folders, so we can move and rename with just one endpoint which makes the code simpler. Previously we were checking if an items was moved, renamed, both or none, now we just call move and that handles it.
=> Remove rename operation
